sudo: false
cache:
  directories:
  - "$HOME/.stack"
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
script:
- stack --no-terminal --skip-ghc-check test
env:
  global:
  - secure: lMVWRVzRUVsbxp1Zce9ezxCRaaFR/+UVpbWT+ElvTQz+1kSs1CccGdMdocKD2edY2mt0hhXDe3jpaZMnW7sTBkrivg76MdAb2UyZDjzj0xXUpcbUB1pweaFGWxE9HkpIq+fb0NkajWgw1wpZqk/+vjU/8RMPBvDkvIHQRtYewY1nnPDpDPP4nUqnKNdPOlDKRsHY66l+XN6ukxXFCqb0PBl4qmzzgbwHpLxNBPgACtPcd4m7wVLVyl1tdiektWhblO4gXME0B8Qm9Ggq1Bbjj0FOqX/rHSalzOpOBeMK8b1hxHehFSkr+Zjqwn34c7IMAZ5zjuOG7vUeHR6iIjtgDSBEPCMsWze/4vb6JGl679LISZ3IQuabBf7sJGfyuCzVLQviCqqDMdzWDPPHNkUmeBGqQUW+awwZBygUTj3dMH2AFDtq1iN0crgxtP9m+awVb+dGpiMfV3iWefiO7ADVvz1Bs+pkmHfJWD0nRDm2rtOw/iRimVnFtfa6QYr53uYnNKTYkqGT65ca4m87+lIwWqU0z5184KTSqHiebZE7/qTZovcwKymM0lW6YdOeMI+O252DbOowaTDIcpNIoDEjtueIfgNhi1T79Es8m8MFvtRWqPCHLm3aTVQwsT0LWR7DAGA95URFG6Cbz811IMWzC2L1cGcT7ELdcmXpTDm7zlg=
  - secure: p4LgpIgqOy5LVThcvotfTqPCDXti8QnlJT7f+EVMogzP8pZXaxT/zBy1iBaRgVVUg7GaDFAOly4LhFDOJHVdsMeXWWZW7zw8awxvzrQr48mS+LeOTjgZs5o9mAcRxc28YzRElWen0yrIXCMb2h8Pn/eJrhijS4xq30AsBlp/tT1QvARicz+VMk2bFiei+9RL3F/TbSPH8rHhUPSE4rS90rioELfErwZ50H4z95khhbd/TH8P8t05F5OXQtKIyaCz9uBIk1R9NDYFLtREjtslldYlOrbml5i7rwJEAnGSp/HeXXy59YUBS32iZVvgLELeTLonVFHIcAU6lBuYG2dScoQolBi0h3MY1u0RORO1ZnNgKfIbhFpRL44I+vRZFyJPIAy/ojcGy6UOpuVieWjCDshWqlTBNM6F70sLMZ4KJcb05Pig55bEP1Ya3A4GlAbzAuVrPTFKQLwNtILDpCDlYsZ1nHtL/pgbKdHK01x8FdFTnb4WWpa+yRweSZRbABctrNl7pDJwC12eFIzT+a06RusspmAqUVdWA/RrdxHyIVmaCGutK3eMbOHhGpczRIddfG/RLogGr5nyfcmcSWB6WRbvdfNtvrssc97I0MvVtn2fY58O2FuvzHiUZJs4831WWHez/5/n0670ZZvWFUYu01VvUThk/rgP/n6i/G1sVY0=
deploy:
  provider: hackage
  username: buesing.marcel@googlemail.com
  password:
    secure: aZypeaEDipQGHXbmmZR1Q85X4Zj1uwzjgcTjcJrAY+q1RW5WZMvg7oIniZAcb6TnBENQbCkyWp2POp+Zoi5teXUsAuDy9GTR/oMb71Xhp7V6aJ3X/Jwvhlek5aQ9drbV5hT/N/DjHTfEgUhRA7/YYAJw5Wm0Y9v+ingo56NO21Wj5iT08EV1oGrARFEYFZj5ja4NZfj3NM3OiOFmiXaAcgPCWljQy6wtJYPrr4O0PrvFodMqUzBnbLwDtAcHaQU47IAxDzatTCT4CIXwDhMLQbYIxVzwwx6Mh2wOh4lePSrFvjh5ajhfW4y3KRNlp6bG5mtaQ0wjNXZ6vTk6tdgODT0qBnawNLJ9VSYDvo2b3V9eR+/RS69glTdaXcfORqzOJvqLAWAFypiJSzz/9eg1dv0hMfhTh59vYQ59k0P8ILhaxeEDL1DlZ87SQe4282f4KvzeofG7W/XIxjLQYQypdJXD/DsJrkSWzI5dI9xBBE0yofeqHSkg1YbfB1st23Psh4LuZglO1NKyQx5OFTn8Wi+K2EFd5/wHG0rLZjYuND3PMzwv/O7MZzpqwvSjRBFxHy8Z7S6Cb38jpr5+tbUyvdlItp/zbeOvU9h5RQ+Ct+7QFWc3mpV9OuA0oD24lEcxfXQB/X9nR+EJxoB3cruID0drqqw6tVVtNyIPMmqNIW0=
  on:
    repo: marcelbuesing/sendgrid-v3
    tags: true
